addpath 'C:\Documents and Settings\Irit\My Documents\MATLAB\DevelopGit\TL_Utils\TL_Utils_V1_5'
addpath 'C:\Documents and Settings\Irit\My Documents\MATLAB\DevelopGit\TL_Utils\TL_Utils_V1_5\motion'
addpath 'C:\Documents and Settings\Irit\My Documents\MATLAB\DevelopGit\ScannerTimeLapse\V15'
addpath 'C:\Users\sivan-nqb\Desktop\nir\NQBMatlab-SubstructBG\TL_Utils\motion'
addpath 'C:\Users\sivan-nqb\Desktop\nir\NQBMatlab-SubstructBG\ScannerTimeLapse\V15'
addpath 'C:\Users\sivan-nqb\Desktop\nir\NQBMatlab-SubstructBG\TL_Utils'
